Status/urls.py
from django.urls import path, include
from .views import view_status

app_name="Status"
urlpatterns = [
    path('', view_status, name="status"),
]

Story6Kefas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Status.urls")),
    path('story7', include("story7.urls")),
    path('story8/', include("story8.urls")),
    path('story9/', include("story9.urls")),
]

story7/urls.py
from django.urls import path, include
from .views import view_story7

app_name="Story7"
urlpatterns = [
    path('', view_story7, name="story7"),
]

story8/urls.py
from django.urls import path, include
from .views import view_story8

app_name="Story8"
urlpatterns = [
    path('', view_story8, name="story8"),
    # path('books/', get_data, name="books")
]

story9/urls.py
from django.urls import path, include
from .views import view_story9, view_login, view_logout

app_name="Story9"
urlpatterns = [
    path('', view_story9, name="story9"),
    path('login/', view_login, name="login"),
    path('logout/', view_logout, name="logout")
]

Status/models.py
from django.db import models
# from django.utils import timezone
# import datetime
# Create your models here.
class Status(models.Model):
    status = models.CharField(max_length=300)
    time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.status

story7/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

# Create your models here.

Status/forms.py
from django import forms
from .models import Status

class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ["status"]
    
    def __init__(self, *args, **kwargs):
        super(StatusForm, self).__init__(*args, **kwargs)

        self.fields["status"].widget.attrs['class'] = "input-status"
        self.fields["status"].widget.attrs['id'] = "input-status"

Status/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status
import datetime
# Create your views here.
def view_status(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            status = form.save(commit=False)
            status.time = datetime.datetime.now()
            status.save()
            return redirect('Status:status')
    else:
        form = StatusForm()
    status_objects = Status.objects.all().order_by("time").reverse()
    return render(request, 'index.html', {"form": form, "status_objects": status_objects})

story7/views.py
from django.shortcuts import render

# Create your views here.
def view_story7(request):
    return render(request, 'story7.html')

story8/views.py
from django.shortcuts import render
import requests
from django.http import JsonResponse

# Create your views here.
def view_story8(request):
    return render(request, 'story8.html')

# def get_data(request):
#     query = request.GET["query"]
#     url = "https://www.googleapis.com/books/v1/volumes?q=" + query 
#     response = requests.get(url)
#     response_json = response.json()

#     return JsonResponse(response_json)

story9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
# @login_required(login_url='/story9/login/')
def view_story9(request):
    return render(request, "home.html")

# def view_signup(request):
#     if request.method == "POST":
#         form = UserCreationForm(request.POST)
#         if form.is_valid():
#             user = form.save()
#             login(request, user)
#             return redirect('/story9')
#     else:
#         form = UserCreationForm()
#     return render(request, 'signup.html', {'form':form})

def view_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('/story9')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})

def view_logout(request):
    logout(request)
    return redirect('/story9')

Status/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Status Kefas</title>
</head>
<body>
    <h1 class="halo">Halo, apa kabar?</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" id="submit" value="post">
    </form>

    {% if status_objects %}
        {% for status in status_objects %}
            <div class="status">
                <h2 class="text">
                    {{ status.status }}
                </h2>
                <p class="time">{{ status.time|date:'d M Y | H:i' }}</p>
            </div>
        {% endfor %}
    {% endif %}
    
</body>
</html>

story7/templates/story7.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'story7.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="{% static 'story7.js' %}"></script>
    <title>Story 7 Kefas</title>
</head>
<body>
    <div class="toggle-container">
        <div class="toggle"></div>
    </div>
    <h1>Hello, I'm Kefas</h1>
    <div class="accordion">
        <div class="item activities">
            <h2 class="title" id="activities">Past Activities and Experiences</h2>
            <div class="desc">
                <p>- Staff of IT Development Department</p>
                <p>- Teaching Assistant of Programming Foundations 1 Course</p>
                <p>- Mentor of Programming Foundations 0</p>
                <p>- Staff of Business-IT Case Competition</p>
                <p>- Software Engineer for Lytebox</p>
            </div>
        </div>
        <div class="item organizations">
            <h2 class="title" id="organizations">Organizations and Committees</h2>
            <div class="desc">
                <p>- BEM PTI Fasilkom UI</p>
                <p>- PO Fasilkom</p>
                <p>- RKF</p>
                <p>- Pesta Rakyat Komputer</p>
            </div>
        </div>
        <div class="item achievements">
            <h2 class="title" id="achievements">Achievements</h2>
            <div class="desc">
                <p>- Cooked a 3-minute instant cup noodles in under 2 minutes</p>
                <p>- Made my mum and dad proud</p>
            </div>
        </div>
    </div>
</body>
</html>

story8/templates/story8.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'story8.css' %}">
    <script
    src="https://code.jquery.com/jquery-3.4.1.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
    crossorigin="anonymous"></script>
    <script src="{% static 'story8.js' %}"></script>
    <title>Story 8 Kefas</title>
</head>
<body>
  <h1>Search for books here!</h1>
    <input type="text" id="search" placeholder="Search">
    <input type="submit" id="button" value="search">
    <table id="results">
        <tr>
          <th>Title</th>
          <th>Book Cover</th>
          <th>Details</th>
        </tr>
      </table>
</body>
</html>

story9/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 9 Kefas</title>
</head>
<body>

    {% if user.is_authenticated %}
    <h1>Hello, {{ user }}</h1>
    <a href="{% url 'Story9:logout' %}">
        <button id="logout">Logout</button>
    </a>
    {% else %}
    <h1>
        Please login!
    </h1>
    <a href="{% url 'Story9:login' %}">
            <button id="login">Login</button>
    </a>
    {% endif %}

</body>
</html>

story9/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Story 9 Login</title>
</head>
<body>
    <form class="auth-form" action="{% url 'Story9:login' %}" method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" id="login" value="Login">
    </form>
</body>
</html>